### ISSUE TITLE
[DeviceMonitor] RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by ErikBjare** [Homebrain/Homebrain#11]
Was just running normally and then I got this:

    Exception in thread DeviceMonitor[1]:                                                                     
    Traceback (most recent call last):                                                                        
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner                                   
        self.run()                                                                                            
      File "/home/erb/Homebrain/homebrain/agents/devicemonitor/devicemonitor.py", line 48, in run             
        openports = self._get_open_ports()                                                                    
      File "/home/erb/Homebrain/homebrain/agents/devicemonitor/devicemonitor.py", line 72, in _get_open_ports 
        pool = ThreadPool(5)                                                                                  
      File "/usr/lib/python3.5/multiprocessing/pool.py", line 749, in __init__                                
        Pool.__init__(self, processes, initializer, initargs)                                                 
      File "/usr/lib/python3.5/multiprocessing/pool.py", line 186, in __init__                                
        self._task_handler.start()                                                                            
      File "/usr/lib/python3.5/threading.py", line 844, in start                                              
        _start_new_thread(self._bootstrap, ())                                                                
    RuntimeError: can't start new thread                                                                      

Perhaps you know what this is about @johan-bjareholt?

**Comment by johan-bjareholt** [comment]
Might have been fixed in the latest commit a4a0052, has to be tested though

**Comment by johan-bjareholt** [comment]
Does it work now? Can i close?

**Comment by ErikBjare** [comment]
Probably works, closing.
